# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

persons: 
  - name: Claudio
    #track: person.claudio
    picture_path: 'images/persons/claudio.jpg'
    more_entities:
      columns: 1 #optional
      entities:
        - entity: sensor.claudios_iphone_battery_state
        - entity: sensor.claudios_iphone_activity
        - entity: sensor.claudios_iphone_last_update_trigger
        - entity: sensor.claudios_iphone_ssid
        - entity: sensor.claudios_iphone_floors_ascended
        - entity: sensor.claudios_iphone_floors_descended
    page_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.claudios_iphone_battery_level
        - entity: sensor.claudios_iphone_steps

  - name: Lucas
    #track: person.lucas
    picture_path: 'images/persons/lucas.png'
    page_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.lg_k220_battery_level
        - entity: sensor.lg_k220_wifi_connection
 
  - name: Viviane
    #track: person.viviane
    picture_path: 'images/persons/viviane.png'

  - name: Cloves
    #track: person.cloves
    picture_path: 'images/persons/cloves.png'
    
  - name: Ana G.
    #track: person.anag
    picture_path: 'images/persons/ana.png'