# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Sala
    icon: fas:couch
    light: light.mesa
    media_player: media_player.sala
#     temperature: sensor.hallway_temperature
#     climate: climate.hallway_climate
#     humidity: sensor.halway_humidity
#     motion: binary_sensor.hallway_sensor_motion
#     door: binary_sensor.hallway_door_contact
#     window: binary_sensor.hallway_window_contact
#     vacuum: 
#       entity: vacuum.rockrobo
#       camera: camera.rockrobo_map
#     plant: plant.hallway_plant
#     more_entities:
#       entities:
#         - entity: sensor.hallway_motion_battery_level
#         - entity: sensor.smokedetector_battery
  - name: Area
    icon: fas:garage
    light: light.area
#     door: group.garage_doors
#     addons:
#       - name: Hello room
#         icon: fas:puzzle-piece
#         path: 'dwains-theme/addons/rooms/hello-room/page.yaml'
#         button_path: 'dwains-theme/addons/rooms/hello-room/button.yaml'
#         data:
#           some_data: 'This is some data parsed.'
#           some_other_data: 'and some other data.'
#           entity: vacuum.roborock
  - name: Quarto Lucas
    icon: fas:bed
    light: light.lampada_quarto
#     more_entities:
#       columns: 2 #optional
#       entities:
#         - entity: sensor.name1
#         - entity: sensor.name2
#     page_entities:
#       columns: 1 #optional
#       entities:
#         - entity: sensor.name1
#         - entity: sensor.name2

  - name: Suite
    icon: fas:bed
    climate: climate.ar_suite